version: 1
lang: en_US # List of languages: ru_RU; en_US;
intervals: 90 # Time is measured in seconds. The interval is set between groups.

groups:
  # Group name: news (can be changed to anything)
  news:
    - ""
    - "<gradient:#8c78ff:#cf9fff><bold>NEWS</bold></gradient> <gray>»</gray> <white>Stay updated with our latest project news!</white>"
    - "&7Follow us on Telegram: <#0088cc><underlined><click:open_url:'https://t.me/yoonaipro'>t.me/yoonaipro</click></underlined></#0088cc>"
    - ""
  # Group name: support
  support:
    - ""
    - "<#8c78ff><bold>SUPPORT</bold> <gray>»</gray> <white>Found a bug or need help? Contact our team.</white>"
    - "&fJoin our community: <#0088cc><underlined><click:open_url:'https://github.com/yoonaipro/Yoo-Announce'>github.com/yoonaipro/Yoo-Announce</click></underlined></#0088cc>"
    - ""
  # Group name: info
  info:
    - ""
    - "<#cf9fff><bold>INFO</bold> <gray>»</gray> <white>Check out our plugins and updates.</white>"
    - "&fVisit our channel: <#0088cc><underlined><click:open_url:'https://t.me/yoonaipro'>t.me/yoonaipro</click></underlined></#0088cc>"
    - ""
